export const GET_POST = 'GET_POST'
export const GET_POST_DB = 'GET_POST_DB'
export const GET_RANDOM_POSTS_A = 'GET_RANDOM_POSTS_A'
export const GET_RANDOM_POSTS_B = 'GET_RANDOM_POSTS_B'
export const SEARCH_POST = 'SEARCH_POST'
export const CLEAR_SEARCH = 'CLEAR_SEARCH'
export const GET_POSTS = 'GET_POSTS'
export const GET_RECENT_POSTS = 'GET_RECENT_POSTS'
